version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.12.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build \
              --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
              --build-arg VERSION=${CIRCLE_TAG} \
              --build-arg VCS_URL=${CIRCLE_REPOSITORY_URL} \
              --build-arg VCS_REF=${CIRCLE_SHA1} \
              -t ${DOCKER_IMAGE_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run:
          name: Login to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Tag Image and Push
          command: |
            docker push ${DOCKER_IMAGE_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
            docker tag ${DOCKER_IMAGE_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} ${DOCKER_IMAGE_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:latest
            docker push ${DOCKER_IMAGE_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:latest
  test:
    working_directory: /app
    docker:
      - image: homesmarthome/ci-manifest:latest
    steps:
      - setup_remote_docker
      - run:
          name: Inspect official alpine image for arm support
          command: |
            [ $(manifest-tool inspect alpine:3.7 | grep -c "Arch: arm") -eq 0 ] && exit 1 || echo arch arm found
      - run:
          name: Inspect official alpine image for amd64 support
          command: |
            [ $(manifest-tool inspect alpine:3.7 | grep -c "Arch: amd64") -eq 0 ] && exit 1 || echo arch amd64 found

workflows:
  version: 2
  build-and-push-and-test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
